### ISSUE TITLE
`make serve` fails on ruby 3.0

### ISSUE THREAD

**Issue by slotThe** [xmonad/xmonad-web#37]
This is not an issue with this repo _per se_, but it is perhaps valuable to write it down somewhere so people can find this information.

With ruby 3.0, `make serve` fails with something like 

    TypeError: no implicit conversion of Hash into Integer

This seems to be caused by [pathutil](https://github.com/envygeeks/pathutil/pull/5) ignoring a deprecation which is now actually a compilation error. 

Further, `webrick` [seems to not be bundle anymore](https://github.com/jekyll/jekyll/issues/8523), which means it has to be added to the `Gemfile`.

#### How to fix it locally

1. Manually apply the [patch](https://patch-diff.githubusercontent.com/raw/envygeeks/pathutil/pull/5.patch) from https://github.com/envygeeks/pathutil/pull/5 to the `pathutil` dir:

   ``` console
   $ pwd
   /home/slot/repos/xmonad/xmonad-web/.bundle/xmonad-gems/ruby/3.0.0/gems/pathutil-0.16.2
   $ patch -p1 < diff.patch
   ```

   there might be some warnings about missing tests, but this can safely be ignored.

2. As pointed out in https://github.com/jekyll/jekyll/issues/8523, add 

   ``` ruby
   gem "webrick", "~> 1.7"
   ```

   to the gemfile or install `webrick` directly with `bundle add webrick`.

3. `make serve` should now work.

**Comment by liskin** [comment]
Do we want to keep https://github.com/xmonad/xmonad-web/commit/eb65e5d425af5f1072a6197051d8cea3afd41413 around?

**Comment by slotThe** [comment]
> Do we want to keep https://github.com/xmonad/xmonad-web/commit/eb65e5d425af5f1072a6197051d8cea3afd41413 around?

Good question.  I don't know ruby's ecosystem well enough; will 2.7 be
around for a while longer or are the changes high it'll be deprecated
soon and distributions will stop packaging it?

**Comment by liskin** [comment]
Absolutely no idea, but also: why is it important? Our Makefile now works with both 2.7 and 3.0, but still prefers 2.7, and we likely no longer need that preference.

**Comment by slotThe** [comment]
Mh, you're probably right.  Let's just revert that then.
